filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
      - /var/log/syslog

output.logstash:
  hosts: ["logstash:5044"]
# output.elasticsearch:
#  hosts: ["http://elasticsearch:9200"]
